config/routes.rb
ActsAsCinemaExampleRails3::Application.routes.draw do
  resources :videos
  root :to => "videos#index"
end

app/models/video.rb
class Video < ActiveRecord::Base
  attr_accessible :title, :url, :description, :original_input, :source_param
  acts_as_cinema :height => 400, :width => 600, :allow_full_screen => false,
                 # You can use a method
                 :tag_template => :aac_tag
                 # Or directly assign a string to the :tag_template option
                 #
                 # :tag_template => %{
                 #   <object width="<%= width %>" height="<%= height %>">
                 #     <param name="movie" value="<%= video_url %>"></param>
                 #     <param name="allowFullScreen" value="<%= allow_full_screen %>"></param>
                 #     <param name="bgcolor" value="#ffffff"></param>
                 #     <param name="allowscriptaccess" value="always"></param>
                 #     <embed src="<%= video_url %>" type="application/x-shockwave-flash" allowscriptaccess="always" 
                 #       allowfullscreen="<%= allow_full_screen %>" width="<%= width %>" height="<%= height %>" wmode="transparent">
                 #     </embed>
                 #   </object>
                 # }
                 
  
  
  
  private  
    # You can customize the tag here
    def aac_tag
      %{
        <object width="<%= width %>" height="<%= height %>">
          <param name="movie" value="<%= video_url %>"></param>
          <param name="allowFullScreen" value="<%= allow_full_screen %>"></param>
          <param name="bgcolor" value="#ffffff"></param>
          <param name="allowscriptaccess" value="always"></param>
          <embed src="<%= video_url %>" type="application/x-shockwave-flash" allowscriptaccess="always" 
            allowfullscreen="<%= allow_full_screen %>" width="<%= width %>" height="<%= height %>" wmode="transparent">
          </embed>
        </object>
      }
    end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  def index
    @videos = Video.all
  end
  
  def show
    @video = Video.find(params[:id])
  end
  
  def new
    @video = Video.new
  end
  
  def create
    @video = Video.new(params[:video])
    if @video.save
      flash[:notice] = "Successfully created video."
      redirect_to @video
    else
      render :action => 'new'
    end
  end
  
  def edit
    @video = Video.find(params[:id])
  end
  
  def update
    @video = Video.find(params[:id])
    if @video.update_attributes(params[:video])
      flash[:notice] = "Successfully updated video."
      redirect_to @video
    else
      render :action => 'edit'
    end
  end
  
  def destroy
    @video = Video.find(params[:id])
    @video.destroy
    flash[:notice] = "Successfully destroyed video."
    redirect_to videos_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    @content_for_title = page_title.to_s
    @show_title = show_title
  end
  
  def show_title?
    @show_title
  end
  
  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end
  
  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
  <head>
    <title><%= h(yield(:title) || "Untitled") %></title>
    <%= stylesheet_link_tag 'application' %>
    <%= yield(:head) %>
  </head>
  <body>
    <div id="container">
      <%- flash.each do |name, msg| -%>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <%- end -%>
      
      <%- if show_title? -%>
        <h1><%=h yield(:title) %></h1>
      <%- end -%>
      
      <%= yield %>
    </div>
  </body>
</html>

app/views/videos/_form.html.erb
<% form_for @video do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :original_input %><br />
    <%= f.text_area :original_input %>
  </p>
  <p><%= f.submit "Submit" %></p>
<% end %>

app/views/videos/edit.html.erb
<% title "Edit Video" %>

<%= render :partial => 'form' %>

<p>
  <%= link_to "Show", @video %> |
  <%= link_to "View All", videos_path %>
</p>

app/views/videos/index.html.erb
<% title "Videos" %>

<table>
  <tr>
    <th>Title</th>
    <th>Original Input</th>
  </tr>
  <% for video in @videos %>
    <tr>
      <td><%=h video.title %></td>
      <td><%=h video.original_input %></td>
      <td><%= link_to "Show", video %></td>
      <td><%= link_to "Edit", edit_video_path(video) %></td>
      <td><%= link_to "Destroy", video, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Video", new_video_path %></p>

app/views/videos/new.html.erb
<% title "New Video" %>

<%= render :partial => 'form' %>

<p><%= link_to "Back to List", videos_path %></p>

app/views/videos/show.html.erb
<% title "Video" %>

<p>
  <strong>Title:</strong>
  <%=h @video.title %>
</p>
<p>
  <strong>Url:</strong>
  <%=h @video.original_input %>
</p>
<p>
  <strong>Watch:</strong>
  <br/>
  <%= raw @video.video_tag %>
</p>

<p>
  <%= link_to "Edit", edit_video_path(@video) %> |
  <%= link_to "Destroy", @video, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", videos_path %>
</p>